version: '3.8'
services:
  web:
    build: .
    image: bvarsani2100/image-upload:latest
    ports:
      - "5000:5000"
    environment:
      -  AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
