name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change to your default branch if different

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-dockerhub-username/your-image-name:latest # Replace with your details

    - name: Deploy to Azure Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: your-azure-app-name # Replace with your Azure app name
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        image: your-dockerhub-username/your-image-name:latest
