name: CI/CD Pipeline image-upload

# Trigger the workflow on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Step 2: Set up Docker Buildx (multi-platform build)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        
    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 4: Build Docker image using docker-compose
    - name: Build the Docker image
      run: docker-compose build

    # Step 5: Tag the Docker image
    - name: Tag the Docker image
      run: docker tag imageupload bvarsani2100/image-upload:latest

    # Step 6: Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push bvarsani2100/image-upload:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Step 7: Deploy to Azure Web App for Containers using the pushed image
    - name: 'Deploy to Azure Web App for Containers'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'imageuploadwa'
        images: 'bvarsani2100/image-upload:latest'
        slot-name: 'production'  # or another slot if you are using staging slots
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
