name: CI/CD Pipeline image-upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker-compose build

    - name: Push Docker image to Docker Hub
      run: docker push bvarsani2100/image-upload:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
  
    - name: Deploy to Azure Web App for Containers
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'imageuploadwa'
        images: 'bvarsani2100/image-upload:latest'
        slot-name: 'production'  
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
        azure-clid: 'az' 
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Restart Azure Web App
      run: |
        az webapp restart --name imageuploadwa --resource-group Learn-azure-AI
